_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 9                     # 8 known + 1 unknown for IDD T1                  
DATASETS:
  TRAIN: ("my_train",)
  TEST: ("my_val",)
SOLVER:
  STEPS: (15000, 18000)
  MAX_ITER: 20000
TEST:
  EVAL_PERIOD: 20000
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 8              # 8 base classes for IDD T1
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"